# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.box_check_update = false
    config.ssh.insert_key = false
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vbguest.auto_update = false
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
   
    config.vm.define "jenkins2021" do|jenkins2021|
      jenkins2021.vm.provision :shell, inline: <<-SHELL
        echo "*** Current user: [`whoami`], Install Jenkins ..."
        sudo yum update -y
        yum install epel-release -y 
        sudo yum install -y java-1.8.0-openjdk-devel
        curl --silent --location http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo | sudo tee /etc/yum.repos.d/jenkins.repo
        sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        sudo yum install -y jenkins
        sudo systemctl start jenkins
      SHELL
    end
  end
  