/** Must install plugin: ssh-steps
 * Groovy List
 * withCredentials()
 * ssh-keygen -m PEM -t rsa -b 4096
 * https://www.cxyzjd.com/article/u010571709/97768340
**/
def _DryRun= true
def remoteVM = [:]
    remoteVM.name = 'ubunt-1'
    remoteVM.host = '34.125.51.112'
    remoteVM.user = 'jack'
    remoteVM.allowAnyHosts = true
node() {
    stage('test') {
        withCredentials([sshUserPrivateKey(credentialsId: "jack_key", keyFileVariable: 'keyFile')]) {
            remoteVM.identityFile = keyFile
            sshCommand remote: remoteVM, dryRun: _DryRun, command: "cat /etc/*release* "
        }
    }
}
