/** Must install plugin: ssh-steps
**/
def remote = [:]
    remote.name = 'test'
    remote.host = '104.199.128.199'
    remote.user = 'skyap'
    remote.allowAnyHosts = true
node() {
    stage('test') {
        withCredentials([sshUserPrivateKey(credentialsId: "skyap", keyFileVariable: 'keyfile')]) {
            remote.identityFile = keyFile
            sshCommand remote: remote, dryRun: false, command: "cat /etc/*release* "
 
        }
    }
}
